"""Release year changed to integer

Revision ID: 0e043e45038f
Revises: efa4a4de2c4c
Create Date: 2025-08-20 01:05:03.371780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e043e45038f"
down_revision: Union[str, Sequence[str], None] = "efa4a4de2c4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "releases",
        "release_year",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="release_year::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "releases",
        "release_year",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="release_year::integer",
    )
    # ### end Alembic commands ###
