"""indices added for fks

Revision ID: d0b1760e07c0
Revises: 6ab9332f25b3
Create Date: 2025-08-11 15:05:11.986505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0b1760e07c0"
down_revision: Union[str, Sequence[str], None] = "6ab9332f25b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_favorites_id"), "favorites", ["id"], unique=False)
    op.create_index(
        op.f("ix_favorites_release_id"), "favorites", ["release_id"], unique=False
    )
    op.create_index(
        op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_release_id"),
        "recommendations",
        ["release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_search_id"),
        "recommendations",
        ["search_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_searches_release_id"), "searches", ["release_id"], unique=False
    )
    op.create_index(op.f("ix_searches_user_id"), "searches", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_searches_user_id"), table_name="searches")
    op.drop_index(op.f("ix_searches_release_id"), table_name="searches")
    op.drop_index(op.f("ix_recommendations_search_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_release_id"), table_name="recommendations")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_release_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_id"), table_name="favorites")
    op.drop_table("favorites")
    # ### end Alembic commands ###
